# Generated by Django 4.1.7 on 2023-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='img',
            field=models.ImageField(default='gallery', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
